# Anaconda configuration file for Socreate OS Server.

[Profile]
profile_id = socreate
base_profile = rhel

[Profile Detection]
os_id = socreate

[Storage]
file_system_type = xfs
default_scheme = LVM

[User Interface]
custom_stylesheet = /usr/share/anaconda/pixmaps/server/socreate-server.css
